version: 0.2

#env:
# variables:
# key: "value"
# key: "value"
#parameter-store:
# key: "value"
# key: "value"
#secrets-manager:
# key: secret-id:json-key:version-stage:version-id
# key: secret-id:json-key:version-stage:version-id
#exported-variables:
# - variable
# - variable
#git-credential-helper: yes
#batch:
#fast-fail: true
#build-list:
#build-matrix:
#build-graph:
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      nodejs:
        12
        # name: version
    commands:
      - docker-compose up --build --d
      - echo Scale Browsers to 5
      - docker-compose scale chrome=5
      # - docker-compose scale firefox=5
      - npm install
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - npx wdio wdio.conf.js
reports:
  wdio-reports:
    files:
      - junitResults/*.xml
    file-format: "JUNITXML"
#base-directory: location
#discard-paths: yes
#file-format: JunitXml | CucumberJson
#artifacts:
#files:
# - location
# - location
#name: $(date +%Y-%m-%d)
#discard-paths: yes
#base-directory: location
#cache:
#paths:
# - paths
